#!/usr/bin/env python

from bs4 import BeautifulSoup
from datetime import datetime
from urllib.request import urlopen
from dateutil.parser import parse as parse_date
from xml.sax.saxutils import escape

def get_item(e):

    a = e.select('h2 a')[0]
    title = a.text.strip()
    url = a.attrs.get('href')

    created = parse_date(e.find('time').text)
    created = created.strftime("%a, %d %b %Y %H:%M:%S +0000")

    # ignore links to this page which changes every day and isn't a permalink
    if url == "https://www.whitehouse.gov/1600daily":
        return None

    title = escape(a.text)
    return """
    <item>
      <title>%s</title>
      <link>%s</link>
      <guid>%s</guid>
      <description>%s</description>
      <pubDate>%s</pubDate>
    </item>
    """ % (title, url, url, title, created)

html = urlopen("https://www.whitehouse.gov/news/").read()
doc = BeautifulSoup(html, "html.parser")
now = datetime.now().strftime("%a, %d %b %Y %H:%M:%S +0000")

print("""<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xml:base="https://www.whitehouse.gov/blog-daily-listings-rss" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>White House - News</title>
    <link>https://www.whitehouse.gov/news/</link>
    <description>An unofficial RSS feed generated by scraping the White House website</description>
    <language>en</language>
    <atom:link href="https://inkdroid.org/rss/whitehouse.xml" rel="self" type="application/rss+xml" />
    <generator>whrss - https://github.com/edsu/whrss</generator>
    <pubDate>%s</pubDate>
""" % now) 

for e in doc.select('article'):
    item = get_item(e)
    if item:
        print(item)

print("""
    </channel>
</rss>
""")
